service: serverless-full-stack
frameworkVersion: "2"

# This will be the new default starting with v3.0.0
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless-zdummy

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: zdummy-sls-bucket
      localDir: uploadData

functions:
  getUser:
    handler: lambdas.getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: zdummy-sls-bucket
